# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d53d23a77e96e8a0bd1337ba77f997d185825e3ed7b3e12d3c9ea07f18fae2314605304f8df9e83549213231a8d3e6159bcd6841ecd22e4175b8aac07482355

test:
  secret_key_base: 5e63b718c0403ca5f6cf549cd2fd9144a662f28f1c5c580a36eb060a3b09f49604896bde4c867c2d1df9ece334ed1fdbaa8dc201cfd34d272b37e6018e382a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d1170011270101a41166a4e218b281210e3cb358cebf787db2d5a6861875ed3c757bbf39c859ffba6cd916aab6f717725905b71230721ba5796819516c2cada3
